spring:
  application:
    name: ecom-application
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*" #or specific ones like: beans, health, info, metrics
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always #or use when-authorized if needed
  info:
    env:
      enabled: true

info:
  app:
    name: MyNewApp
    description: MyNewApp
    version: 1.0.0

